### ISSUE TITLE
readme中2.3数据分布的问题

### ISSUE THREAD

**Issue by hbbOooO** [GJSeason/CCL2023-FCC#1]
您好，
感谢您对本次评测活动的组织。
我对这次的活动很感兴趣，所以将发布的数据集下载到本地查看，当我准备进行实验时，发现了一个细节的问题：
readme文件中的类别“冒充军警购物类”，在数据集中名为“冒充军警购物类诈骗”。

**Comment by GJSeason** [comment]
参赛者您好，
感谢您的细心发现，您所描述的问题确实存在。
经检查，发布的数据是经反诈平台导出的，其在平台中标注即为“冒充军警购物类诈骗”，而其他类别标注均无“诈骗”后缀。因此在数据处理时未能及时发现这一问题，已在 README 和 Codalab 中更新这一问题描述。
再次感谢您对本次评测的参与和支持！
