### ISSUE TITLE
数据标签错误

### ISSUE THREAD

**Issue by xxllp** [GJSeason/CCL2023-FCC#2]
这个train数据我看有一些标签不太对的，真正的test标签是否经过校验呢

**Comment by GJSeason** [comment]
参赛者您好，
数据集（含标注）来源于反诈数据平台，标签是用户在上传到平台时给出的，可能存在标注错误的情况。测试集和训练集都是从原始数据中划分的，没有进行过专门的校验。
感谢您对本次评测的参与和支持！
