### ISSUE TITLE
能否延长时间或在评测结束后公开数据集？

### ISSUE THREAD

**Issue by SupritYoung** [GJSeason/CCL2023-FCC#3]
由于拿到数据的时间比较晚，方法比较复杂，运算量较大，可能无法按时（5 月 10 日）完成结果提交。但依然想取得测试集结果。请问主办方是否考虑延长比赛时间或者赛后公开测试集？后续投稿论文定会感谢主办方的贡献。

**Comment by GJSeason** [comment]
参赛者您好，
①关于是否延长时间的决定，鉴于比赛只剩余约16小时且之前并未有延长打算，若临时变更计划延长时间，恐对其他参赛者和组织方的进度安排造成一定影响，因此组织方决定按原计划时间（即UTC时间 5月10日 23:59:59）结束比赛。
②关于是否公开测试集的决定，组织方需要一定时间考虑，若最终决定公开测试集，会在评测说明页面更新发布，并通过邮件通知每位参赛者。
③考虑到您想取得测试集结果，若比赛结束无法提交且尚未公开测试集，可以随时通过邮件形式将文件提交至比赛联系邮箱，届时将由组织方在本地测试您的文件，并提供结果回复与您，以供参考。
感谢您对本次评测的支持与参与！若有问题可随时邮件咨询评测联系邮箱！
